# fly.toml corrected for Vanilla Terraria server on Fly.io
app = "terraria-vainilla-server"

primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  WORLD_NAME = "Puerto"
  WORLD_SIZE = "3"
  WORLD_SEED = "fire"
  DIFFICULTY = "3"
  MAX_PLAYERS = "16"
  PASSWORD = "secret"
  MOTD = "Bienvenidos al server de Killtrayer 🤘"

[processes]
  app = "/terraria-server/TerrariaServer.bin.x86_64 -server -world /root/.local/share/Terraria/Worlds/Puerto.wld -autocreate 3 -maxplayers 16 -password secret -difficulty 3 -seed fire"

[mounts]
  source = "terraria_data"
  destination = "/root/.local/share/Terraria/Worlds"

[[services]]
  processes = ["app"] # Link this service to the 'app' process
  internal_port = 7777
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 7777

[[services]]
  processes = ["app"] # Link this service to the 'app' process
  internal_port = 7777
  protocol = "udp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 7777

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

